server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: health, info
spring:
  application:
    name: config-service
  profiles:
    active: local
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fredo1975/spring-cloud-server-config.git
          skipSslValidation: true
          clone-on-start: false
          
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false